# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'WSSketch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

#  pod 'Socket.IO-Client-Swift', '~> 13.2.0'
  # Pods for WSSketch

end
